### ISSUE TITLE
Floating action button moves up when used with keyboard input

### ISSUE THREAD

**Issue by stijnie2210** [bizz84/bottom_bar_fab_flutter#2]
First of all, I'm very grateful for this code to exist! But since i've been using it i've been coming across a couple layout bugs.

The first one is, when i'm using the code from the example there seems to be two FABs, and one seems to be lower than the other the first time the app boots up. 
![screen1](https://user-images.githubusercontent.com/8982310/48120501-93e1d480-e272-11e8-9de9-58e9a55e5955.png)

again, this is with the exact code from the repo, besides some text and theme changes ofcourse.

The second problem is when you tap on a text field and the keyboard pops up, the FAB moves up as well, and stays there even when you close the keyboard, as seen in the screenshots below. Maybe I'm doing something wrong here, but I'd appreciate some feedback.

![screen3](https://user-images.githubusercontent.com/8982310/48120570-c68bcd00-e272-11e8-8b4a-2263f1b57a42.png)

![screen2](https://user-images.githubusercontent.com/8982310/48120575-cab7ea80-e272-11e8-8335-76c54813d056.png)

Thank you very much in advance!

**Comment by vvasc** [comment]
to correct that, you could make a new class of FixedCenterDockedFabLocation extends FloatingActionButtonLocation and pass the context to it.


it's something like: 

```
import 'dart:math';

import 'package:flutter/material.dart';

class FixedCenterDockedFabLocation extends FloatingActionButtonLocation {
  const FixedCenterDockedFabLocation({
    this.context,
  });
  final context;

  @protected
  double getDockedY(ScaffoldPrelayoutGeometry scaffoldGeometry) {
    final double contentBottom = scaffoldGeometry.contentBottom;
    final double bottomSheetHeight = scaffoldGeometry.bottomSheetSize.height;
    final double fabHeight = scaffoldGeometry.floatingActionButtonSize.height;
    final double snackBarHeight = scaffoldGeometry.snackBarSize.height;
    double bottomDistance = MediaQuery.of(context).viewInsets.bottom;

    double fabY = contentBottom + bottomDistance - fabHeight / 2.0;

    // The FAB should sit with a margin between it and the snack bar.
    if (snackBarHeight > 0.0)
      fabY = min(fabY, contentBottom - snackBarHeight - fabHeight - kFloatingActionButtonMargin);
    // The FAB should sit with its center in front of the top of the bottom sheet.
    if (bottomSheetHeight > 0.0)
      fabY = min(fabY, contentBottom - bottomSheetHeight - fabHeight / 2.0);

    final double maxFabY = scaffoldGeometry.scaffoldSize.height - fabHeight;
    return min(maxFabY, fabY);
  }
  @override
  Offset getOffset(ScaffoldPrelayoutGeometry scaffoldGeometry) {
    final double fabX = (scaffoldGeometry.scaffoldSize.width - scaffoldGeometry.floatingActionButtonSize.width) / 2.0;
    return Offset(fabX, getDockedY(scaffoldGeometry));
  }
}
```

![image](https://user-images.githubusercontent.com/31106223/51411161-ffd39980-1b4d-11e9-92d8-28200a3d599b.png)


![image](https://user-images.githubusercontent.com/31106223/51411113-d31f8200-1b4d-11e9-8083-72d15aa81ffe.png)

**Comment by aytunch** [comment]
@vvasc Thanks for this solution, I implemented it and now the FAB does not go up along with the keyboard. However the FAB makes a scale down to 0pixels and back up to its original size animation when the textfield is on focus. You can see it behind the keyboard in iOS simulator with a semi transparent keyboard. 

Also, in my case, when i change through tabs of my bottomnavbar the same thing happens. Is this something about passing the context? Could you be so kind and check this issue?

**Comment by vvasc** [comment]
This happens with me too, unfortunately I don't know what causes that. But I've another approach which consist in apply a new fabLocation only when the keyboard appear.

```
static _dockedFabLocation(context) {
    if (MediaQuery.of(context).viewInsets.bottom != 0) {
      return FixedCenterDockedFabLocation(bottomDistance: MediaQuery.of(context).viewInsets.bottom);
    } else {
      return FloatingActionButtonLocation.centerDocked;
    }
  }
```
And FixedCenterDockedFabLocation still is the class above.
In this case I send the position of bottom distance instead of send `context` and the fab continues to make an animation when keyboard appear, however when I change tabs the FAB don't animate.

I know this one does not the best solution because the problem with animation FAB, although, this is the only solution I found to use an AppBar with a center FAB.

**Comment by srineesh** [comment]
how to navigate between other pages, when clicked items in the bottom bar without setting up a default index. 
Thank you in advance.

**Comment by aarajput** [comment]
> @vvasc Thanks for this solution, I implemented it and now the FAB does not go up along with the keyboard. However the FAB makes a scale down to 0pixels and back up to its original size animation when the textfield is on focus. You can see it behind the keyboard in iOS simulator with a semi transparent keyboard.
> 
> Also, in my case, when i change through tabs of my bottomnavbar the same thing happens. Is this something about passing the context? Could you be so kind and check this issue?

Code from https://github.com/bizz84/bottom_bar_fab_flutter/issues/2#issuecomment-455675962 needs to be fixed in order to fix animation issue.

1. Make `FixedCenterDockedFabLocation` **const** and dont pass context in it.  I am asking you to this because animation on fab happens if `FixedCenterDockedFabLocation` rebuilds. **const** keyword will avoid that. 
2. Instead of `double bottomDistance = MediaQuery.of(context).viewInsets.bottom;`, use `double bottomDistance = WidgetsBinding.instance.window.viewInsets.bottom`

**Comment by sils** [comment]
For future reference, this is an implementation following this idea minus a few quirks, with less lines of code and using more upstream code, i.e. hopefully better to maintain:

```
class FixedCenterDockedFabLocation extends StandardFabLocation
    with FabCenterOffsetX, FabDockedOffsetY {
  const FixedCenterDockedFabLocation();

  @override
  String toString() => 'FloatingActionButtonLocation.fixedCenterDocked';

  @override
  double getOffsetY(
      ScaffoldPrelayoutGeometry scaffoldGeometry, double adjustment) {
    final double bottomMinInset = scaffoldGeometry.minInsets.bottom;
    if (bottomMinInset > 0) {
      // Hide if there's a keyboard
      return 0;
    }
    return super.getOffsetY(scaffoldGeometry, adjustment);
  }
}
```

Feel free to use this code without limitations or attribution.

Also note that when using this, use it with `const`.

**Comment by JamiuJimoh** [comment]
> For future reference, this is an implementation following this idea minus a few quirks, with less lines of code and using more upstream code, i.e. hopefully better to maintain:
> 
> ```
> class FixedCenterDockedFabLocation extends StandardFabLocation
>     with FabCenterOffsetX, FabDockedOffsetY {
>   const FixedCenterDockedFabLocation();
> 
>   @override
>   String toString() => 'FloatingActionButtonLocation.fixedCenterDocked';
> 
>   @override
>   double getOffsetY(
>       ScaffoldPrelayoutGeometry scaffoldGeometry, double adjustment) {
>     final double bottomMinInset = scaffoldGeometry.minInsets.bottom;
>     if (bottomMinInset > 0) {
>       // Hide if there's a keyboard
>       return 0;
>     }
>     return super.getOffsetY(scaffoldGeometry, adjustment);
>   }
> }
> ```
> 
> Feel free to use this code without limitations or attribution.
> 
> Also note that when using this, use it with `const`.

This works but the fab gets pushed to the top of the screen and still visible. A work around I used was to "return -100". This way, it gets pushed off the screen.
