### ISSUE TITLE
FAB not Disappearing when Navigator.push to other scaffold widget

### ISSUE THREAD

**Issue by SimonPeter1909** [bizz84/bottom_bar_fab_flutter#6]
I have successfully implemented FABBottomAppBar in my app. 
My app flow - click on the area to display the list of connection in the area.
But the fab is still visible when I push a new Scaffold Widget.

Screenshots below :
**First Layout:**
![Screenshot_2019-06-02-18-58-47-880](https://user-images.githubusercontent.com/24413796/58762036-bddd4a00-8568-11e9-89a9-ebe0ecdf8a21.jpeg)
**Second Layout:**
![Screenshot_2019-06-02-19-00-25-324](https://user-images.githubusercontent.com/24413796/58762037-be75e080-8568-11e9-8bd4-bc80c325b336.jpeg)

**Comment by mdanics** [comment]
What was your fix for this?

**Comment by SimonPeter1909** [comment]
I have just used bubble_bottom_bar plugin...
